import org.ihtsdo.drools.domain.Concept
import org.ihtsdo.drools.domain.Relationship
import org.ihtsdo.drools.domain.Constants
import org.ihtsdo.drools.response.InvalidContent
import org.ihtsdo.drools.helper.RelationshipHelper
import java.util.ArrayList
import org.ihtsdo.drools.service.ConceptService

global java.util.List invalidContent
global ConceptService conceptService

rule "Metadata concepts must be in the model module (not the core module)."
	dialect "mvel"
	when
		c : Concept(active, moduleId != "900000000000012004")
		topLevelHierarchies : ArrayList() from collect( String() from conceptService.findTopLevelHierarchiesOfConcept(c))
		Concept(topLevelHierarchies contains "900000000000441003")
	then
		InvalidContent invalid = new InvalidContent("8fb51c28-3194-4917-aea3-f58f1dcc9cd2",
				c, "Metadata concepts must be in the model module (not the core module).");
		invalid.ignorePublishedCheck();
		invalidContent.add(invalid);
end
